/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "drv/comms/config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Config, Config, 2)


PB_BIND(Config_Callibration, Config_Callibration, AUTO)


PB_BIND(Config_PidConfig, Config_PidConfig, AUTO)


PB_BIND(Config_FootPadSettings, Config_FootPadSettings, AUTO)


PB_BIND(Config_BalancingConfig, Config_BalancingConfig, AUTO)


PB_BIND(Config_PusbackSettings, Config_PusbackSettings, AUTO)


PB_BIND(Config_Misc, Config_Misc, AUTO)


PB_BIND(Config_LoadLift, Config_LoadLift, AUTO)



