/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Mon Dec 17 22:37:30 2018. */

#include "protocol.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const float Config_balance_expo_default = 1;
const float Config_balance_angle_scaling_default = 1;
const float Config_beep_rc_default = 0.05;
const float Config_beep_threshold_default = 0.75;
const int32_t Config_Callibration_acc_x_default = 0;
const int32_t Config_Callibration_acc_y_default = 0;
const int32_t Config_Callibration_acc_z_default = 0;
const float Config_PidConfig_p_default = 175;
const float Config_PidConfig_d_default = 0.35;
const float Config_PidConfig_i_default = 0.05;
const float Config_PidConfig_max_i_default = 10000;
const float Config_FootPadSettings_filter_rc_default = 0.05;
const int32_t Config_FootPadSettings_min_level_to_start_default = 3700;
const int32_t Config_FootPadSettings_min_level_to_continue_default = 3500;


const pb_field_t Config_fields[8] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, Config, callibration, callibration, &Config_Callibration_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, Config, balance_pid, callibration, &Config_PidConfig_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, Config, foot_pad, balance_pid, &Config_FootPadSettings_fields),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, Config, balance_expo, foot_pad, &Config_balance_expo_default),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, Config, balance_angle_scaling, balance_expo, &Config_balance_angle_scaling_default),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, Config, beep_rc, balance_angle_scaling, &Config_beep_rc_default),
    PB_FIELD(  7, FLOAT   , OPTIONAL, STATIC  , OTHER, Config, beep_threshold, beep_rc, &Config_beep_threshold_default),
    PB_LAST_FIELD
};

const pb_field_t Config_Callibration_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, Config_Callibration, acc_x, acc_x, &Config_Callibration_acc_x_default),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Config_Callibration, acc_y, acc_x, &Config_Callibration_acc_y_default),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, Config_Callibration, acc_z, acc_y, &Config_Callibration_acc_z_default),
    PB_LAST_FIELD
};

const pb_field_t Config_PidConfig_fields[5] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, Config_PidConfig, p, p, &Config_PidConfig_p_default),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, Config_PidConfig, d, p, &Config_PidConfig_d_default),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, Config_PidConfig, i, d, &Config_PidConfig_i_default),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, Config_PidConfig, max_i, i, &Config_PidConfig_max_i_default),
    PB_LAST_FIELD
};

const pb_field_t Config_FootPadSettings_fields[4] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, Config_FootPadSettings, filter_rc, filter_rc, &Config_FootPadSettings_filter_rc_default),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, Config_FootPadSettings, min_level_to_start, filter_rc, &Config_FootPadSettings_min_level_to_start_default),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, Config_FootPadSettings, min_level_to_continue, min_level_to_start, &Config_FootPadSettings_min_level_to_continue_default),
    PB_LAST_FIELD
};

const pb_field_t Stats_fields[10] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, Stats, batt_voltage, batt_voltage, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, Stats, batt_current, batt_voltage, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, Stats, motor_current, batt_current, 0),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, Stats, speed, motor_current, 0),
    PB_FIELD(  6, FLOAT   , OPTIONAL, STATIC  , OTHER, Stats, distance_traveled, speed, 0),
    PB_FIELD(  7, FLOAT   , REQUIRED, STATIC  , OTHER, Stats, drive_angle, distance_traveled, 0),
    PB_FIELD(  8, FLOAT   , REQUIRED, STATIC  , OTHER, Stats, stear_angle, drive_angle, 0),
    PB_FIELD(  9, UINT32  , REQUIRED, STATIC  , OTHER, Stats, pad_pressure1, stear_angle, 0),
    PB_FIELD( 10, UINT32  , REQUIRED, STATIC  , OTHER, Stats, pad_pressure2, pad_pressure1, 0),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Config, callibration) < 65536 && pb_membersize(Config, balance_pid) < 65536 && pb_membersize(Config, foot_pad) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_Config_Config_Callibration_Config_PidConfig_Config_FootPadSettings_Stats)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(Config, callibration) < 256 && pb_membersize(Config, balance_pid) < 256 && pb_membersize(Config, foot_pad) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_Config_Config_Callibration_Config_PidConfig_Config_FootPadSettings_Stats)
#endif


/* @@protoc_insertion_point(eof) */
